apiVersion: apps/v1
kind: Deployment
metadata:
  name: grandnode
spec:
  selector:
    matchLabels:
      run: grandnode
  replicas: 1
  template:
    metadata:
      labels:
        run: grandnode
    spec:
      containers:
      - name: grandnode
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 80
